name: Releases

# 触发条件
on:
  push:
    tags:
      - 'v*'

jobs:
  release-windows:
    # windows用户执行的是.exe
    runs-on: windows-latest
    steps:
      # 拉取项目代码
      - name: Checkout code
        uses: actions/checkout@v3
      # 安装python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      # 安装依赖
      - name: Install dependencies
        run: |
          pip install pyautogui
          pip install opencv-python
          pip install pygetwindow
          pip install pyqt6
          pip install pyinstaller
      # Build
      - run: sh deploy.sh
      # Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          # 供用户下载使用的最终产物
          artifacts: "dist/LangrisserHelper.tar.gz"
          # 相对于项目根路径
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN  }}
